dist: jammy
sudo: required
language: python
python: "3.11"

before_install:
  - nvm install 20.16.0

install:
  - echo -e '@neverendingsupport:registry=https://registry.nes.herodevs.com/npm/pkg/\n//registry.nes.herodevs.com/npm/pkg/:_authToken="'${NES_AUTH_TOKEN}'"' > .npmrc
  - npm install
  - pip3 install tox

script:
  - psql -c 'create database bugenhagen_test;' -U postgres
  - psql bugenhagen_test -c 'create extension pg_trgm;' -U postgres
  - psql bugenhagen_test -c "create role damien superuser login password 'damien'; alter schema public owner to damien;" -U postgres
  - pip3 install -r requirements.txt
  - tox --parallel || travis_terminate 1

services:
  - postgresql
