# Tox (https://tox.readthedocs.io/) is a tool for running tests in multiple virtualenvs.

[tox]
envlist =
    lint-py,
    test,
    lint-vue,
    build-vue
skipsdist = True

[testenv]
allowlist_externals = *

[testenv:lint-vue]
commands = npm run lint-vue {posargs}

[testenv:lint-vue-fix]
commands = npm run lint-vue-fix {posargs}

[testenv:build-vue]
commands = npm run build-vue

[testenv:test]
# On Travis we access Postgres 12 at port 5433; pass on the PGPORT variable for test runs.
setenv =
    PGPORT = {env:PGPORT:5432}
commands = pytest {posargs: -p no:warnings tests}

[testenv:lint-py]
commands = ruff check {posargs:application.py config consoler.py damien scripts tests mrsbaylock}
